name: Deploy
on:
  schedule:
    - cron: '0 0 * * *'
  push:
    branches:
      - 'master'
env:
  DIGITALOCEAN_ACCESS_TOKEN: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  CLOUDFLARE_EMAIL: ${{ secrets.CLOUDFLARE_EMAIL }}
  CLOUDFLARE_API_KEY: ${{ secrets.CLOUDFLARE_API_KEY }}
jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Python Setup
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Python Packages
        run: pip install --no-cache-dir --upgrade octodns octodns_cloudflare octodns_digitalocean
      - name: OctoDNS Validate
        run: octodns-validate --config-file ${{ github.workspace }}/config.yml
      - name: OctoDNS Sync (Dryrun)
        run: octodns-sync --config-file ${{ github.workspace }}/config.yml > /dev/null 2>&1
      - name: OctoDNS Sync
        run: octodns-sync --config-file ${{ github.workspace }}/config.yml --doit > /dev/null 2>&1
